routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Spatie\Honeypot\ProtectAgainstSpam;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::name('web.')->group(function() {
    Route::name('site.')->group(function () {
        Route::get('/', 'HomeController@view')->name('home');
        Route::get('/contact', 'ContactController@view')->name('contact');
        Route::get('/data', 'DataController@view')->middleware(['auth'])->name('data');
        Route::post('/getOceanData', 'DataController@getOceanData')->middleware(['auth'])->name('oceanData');
    });
});

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLogin')->name('login');
Route::post('doLogin', 'Auth\LoginController@login')->middleware(ProtectAgainstSpam::class)->name('doLogin');
Route::get('logout', 'Auth\LoginController@logout')->name('logout');
Route::get('register', 'Auth\RegisterController@showRegister')->name('register');
Route::post('doRegister', 'Auth\RegisterController@register')->middleware(ProtectAgainstSpam::class)->name('doRegister');

app/Models/MetOceanData.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class MetOceanData extends Model
{
    use HasFactory;
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Contracts\Auth\Access\Authorizable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/ContactController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class ContactController extends Controller
{
    public function view() {
        return view('site.contact');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/DataController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class DataController extends Controller
{
    public function view() {
        return view('site.data');
    }
    public function getOceanData() {
        $oceanData = DB::table('met_ocean_data')
            ->orderBy('Time', 'ASC')
            ->get();
        return response()->json($oceanData);
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    public function view() {
        return view('site.index');
    }
}

app/Http/Controllers/MetOceanDataController.php
<?php

namespace App\Http\Controllers;

use App\Models\MetOceanData;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class MetOceanDataController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function index()
    {
        $oceanData = DB::table('met_ocean_data')
            ->orderBy('Time', 'ASC')
            ->get();
        return response()->json($oceanData);
    }
}

resources/views/layouts/site.blade.php
<!DOCTYPE html>
    <html lang="{{ app()->getLocale() }}" dir="ltr">
    <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <link rel="alternate" hreflang="en-NZ" href="{{ env('APP_URL') }}"/>
        <title>@yield('title') | {{ __('general.company') }}</title>
        <link rel="shortcut icon" href="{{ secure_asset('/img/favicon.ico') }}">
        <meta name="description" content="@yield('description')">
        <meta name="keywords"   content="@yield('keywords')" />
        <meta name="robots" content="index, follow" />
        <meta property="og:title" content="@yield('title') | {{ __('general.company') }}" />
        <meta property="og:description" content="@yield('description')" />
        <meta property="og:type" content="website" />
        <meta property="og:locale" content="{{ app()->getLocale() }}-NZ" />
        <meta property="og:site_name" content="Met Ocean Analytics" />
        <meta property="og:url" content="{{ url()->full() }}" />
        <meta property="og:image" content="{{ secure_asset('/img/site/wonder-water-unit.png') }}" />
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,400i,700|Raleway:300,400,500,600,700|Crete+Round:400i" rel="stylesheet" type="text/css" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <link rel="stylesheet" href="{{ mix('css/app.css') }}" type="text/css" />
        <link rel="stylesheet" href="{{ mix('css/moa.css') }}" type="text/css" />
    </head>
    <body class="stretched sticky-responsive-menu no-transition">
    <div id="wrapper" class="clearfix">
        <div id="moa-app">
            @include('partials.site.header')
            @yield('slider')
            <section id="content" class="ww-pd-0px">
                @yield('content')
            </section>
        </div>
    </div>
    <div id="gotoTop" data-mobile='true' class="icon-angle-up">
    </div>

    <script src="{{ mix('js/app.js') }}"></script>

    </body>
</html>

resources/views/partials/site/header.blade.php
<header id="header" class="navbar navbar-expand-md navbar-light bg-light bd-navbar">
    <nav class="container-xxl flex-wrap flex-md-nowrap" aria-label="Main navigation">
        <a href="{{route('web.site.home')}}" class="navbar-brand"
           data-dark-logo="{{ secure_asset("/img/logo.png") }}" >
            <img src="{{ secure_asset("/img/logo.png") }}" alt="{{__('general.company')}}" width="100" height="100">
        </a>
        <div class="collapse navbar-collapse" id="moa-navbar">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link {{ set_active(['/']) }}" aria-current="page" href="{{route('web.site.home')}}" title="{{ __('general.home_page') }}">{{__('general.home_page')}}</a>
                </li>
                @auth
                    <li class="nav-item">
                        <a class="nav-link {{ set_active(['data*']) }}" href="{{ route('web.site.data') }}" title="{{ __('general.data') }}">{{ __('general.data') }}</a>
                    </li>
                @endauth
{{--                <li class="nav-item">--}}
{{--                    <a class="nav-link {{ set_active(['contact*']) }}" href="{{ route('web.site.contact') }}" title="{{ __('general.contact') }}">{{ __('general.contact') }}</a>--}}
{{--                </li>--}}
            </ul>
            <div class="navbar-nav d-flex float-end">
                @auth
                    <span class="navbar-text pr-2">Welcome {{ Auth::user()->name }}</span>
                    <a class="nav-link" aria-current="page" href="{{route('logout')}}" title="{{ __('general.logout') }}">{{__('general.logout')}}?</a>
                @endauth

                @guest
                    <a class="nav-link {{ set_active(['login*']) }}" aria-current="page" href="{{route('login')}}" title="{{ __('general.login') }}">{{__('general.login')}}</a>
                    <a class="nav-link {{ set_active(['register*']) }}" aria-current="page" href="{{route('register')}}" title="{{ __('general.register') }}">{{__('general.register')}}</a>
                @endguest
            </div>
        </div>
    </nav>
</header>

resources/views/site/contact.blade.php
@extends('layouts.site',['header' => 'transparent-header'])
@section('title', __('general.contact_title'))
@section('description', __('general.contact_description'))
@section('keywords', __('general.contact_keywords'))

@section('slider')
    <section id="slider" class="slider-element slider-parallax swiper_wrapper full-screen clearfix force-full-screen floating-header dont-deduct-height-off" data-autoplay="7000" data-speed="750" data-loop="false">

        <div class="slider-parallax-inner">

            <div class="swiper-container swiper-parent swiper-container-horizontal">
                <div class="swiper-wrapper">
                    <div class="d-flex flex-direction-nav align-items-center swiper-slide dark" style="background-image: url('{{ secure_asset('/img/home_background.jpg') }}') ; background-size: cover;" data-swiper-slide-index="0">
                        <div class="container clearfix">
                            <div class="col_full vertical-middle dark fright nobottommargin fadeIn animated text-center" style="top: -63px; position: relative;">
                                <h3 class="slogan">It's a matter</h3>
                                <div class="emphasis-title">
                                    <h2 class="slogan ww-fw-900 text-uppercase">Of taste</h2>
                                </div>
                            </div>

                        </div>
                    </div>

                </div>
            </div>
            <a href="#" data-scrollto="#content" data-offset="100" class="dark one-page-arrow">
                <i class="icon-angle-down infinite animated fadeInDown"></i>
            </a>
        </div>

    </section>
@endsection

resources/views/site/data.blade.php
@extends('layouts.site',['header' => 'transparent-header'])
@section('title', __('general.home_page_title'))
@section('description', __('general.home_page_description'))
@section('keywords', __('general.home_page_keywords'))

@section('content')
    <oceandata></oceandata>
@endsection

resources/views/site/index.blade.php
@extends('layouts.site',['header' => 'transparent-header'])
@section('title', __('general.home_page_title'))
@section('description', __('general.home_page_description'))
@section('keywords', __('general.home_page_keywords'))

@section('slider')
    <section id="slider" class="slider-element slider-parallax swiper_wrapper full-screen clearfix force-full-screen floating-header dont-deduct-height-off" data-autoplay="7000" data-speed="750" data-loop="false">

        <div class="slider-parallax-inner">

            <div class="swiper-container swiper-parent swiper-container-horizontal">
                <div class="swiper-wrapper">
                    <div class="d-flex flex-direction-nav align-items-center swiper-slide dark" style="background-image: url('{{ secure_asset('/img/home_background.jpg') }}') ; background-size: cover;" data-swiper-slide-index="0">
                        <div class="container clearfix">
                            <div class="col_full vertical-middle dark fright nobottommargin fadeIn animated text-center" style="top: -63px; position: relative;">
                                <h1 class="pb-3">Make a more informed decision today.</h1>
                                <h3 class="pb-3">Get the best interactive data with MetOcean Analytics</h3>
                                <a href="{{ route('web.site.data') }}" class="btn btn-primary btn-lg">You Won't Look Back!</a>
                            </div>

                        </div>
                    </div>

                </div>
            </div>
            <a href="#" data-scrollto="#content" data-offset="100" class="dark one-page-arrow">
                <i class="icon-angle-down infinite animated fadeInDown"></i>
            </a>
        </div>

    </section>
@endsection